# all services
services:
  - type: web
    name: pwa-sveltekit
    runtime: static
    buildCommand: npm i -g pnpm; pnpm install --production=false; pnpm build
    staticPublishPath: ./build
    # pullRequestPreviewsEnabled: true # optional
    # headers:
    #   - path: /*
    #     name: X-Frame-Options
    #     value: sameorigin
    # routes:
    #   - type: redirect
    #     source: /old
    #     destination: /new
    #   - type: rewrite
    #     source: /a/*
    #     destination: /a
